### ISSUE TITLE
Add gstreamer dependencies

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/mycroft-devices#34]
For video playback we need to add the gstreamer dependencies. 

Doing a blanket install works, but I'm assuming we don't need all of these?

```
- libgstreamer1.0-0
- gstreamer1.0-plugins-base
- gstreamer1.0-plugins-good
- gstreamer1.0-plugins-bad
- gstreamer1.0-plugins-ugly
- gstreamer1.0-libav
- gstreamer1.0-doc
- gstreamer1.0-tools
- gstreamer1.0-x
- gstreamer1.0-alsa
- gstreamer1.0-gl
- gstreamer1.0-gtk3
- gstreamer1.0-qt5
- gstreamer1.0-pulseaudio
- libqt5multimedia5-plugins
```

**Comment by forslund** [comment]
You might check the [gstreamer-packages.yml](https://github.com/MycroftAI/mycroft-devices/blob/master/recipes/gstreamer-packages.yml) for the ones used in the bionic image.

That specific set didn't work on Focal but might indicate which packages are required. (I believe some were not found at the time)

**Comment by forslund** [comment]
Seems like the fluendo-mp3 plugin is the issue. Can that just be dropped @AIIX ?

**Comment by forslund** [comment]
It looks like I should be able to add a replacement package to the mycroft-alternatives repo if it's needed / good to have...

Edit: No it'll likely be hard...

**Comment by forslund** [comment]
Reading https://bugs.launchpad.net/ubuntu/+source/ubuntu-restricted-addons/+bug/1798831 suggests that gstreamer-plugins-good should cover the mp3 case and fluendo-mp3 can be dropped from the deps
